<?php
/**
 * @file
 * Provide an grid_alpha_omega display style for Views.
 *
 * This is a placeholder file so drupal will enable the module. All logic is contained in
 * other files located with the module.
 */

/**
 * Implementation of hook_views_api().
 */
function views_grid_alpha_omega_views_api() {
  return array('api' => 2);
}

/**
 * Template function for views_grid_alpha_omega style plugin
 *
 * @param array $vars
 *  Array of template variables.
 *
 * The JS file is loaded within render() in views_grid_alpha_omega_style_plugin.inc
 */
function template_preprocess_views_view_grid_alpha_omega(&$vars) {
  // inherit the normal unformatted classes
  template_preprocess_views_view_unformatted($vars);
  $vars['total_columns'] = empty($vars['options']['total_columns']) ? 12 : $vars['options']['total_columns'];
  $vars['grid_width'] = empty($vars['options']['grid_width']) ? 3 : $vars['options']['grid_width'];
}