<?php
/**
* Implements hook_entity_info_alter().
*/

function custom_view_modes_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['listing'] = array(
    'label' => t('Attendees'),
    'custom settings' => 'TRUE',
  );
  
} 

/**
* Implements hook_preprocess_node().
*/
function custom_view_modes_preprocess_node(&$vars) {
  if($vars['view_mode'] == 'listing') {
    $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__listing';
  }
  if($vars['view_mode'] == 'sponsor') {
      $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__sponsor';
    }
}

function custom_view_modes_theme($existing) {
  return array(
    'views_view__viewname__displayid' => array (
    'arguments' => array('view' => NULL),
    'template' => 'views-view--viewname--displayid',
    'base hook' => 'views_view',
    'path' => drupal_get_path('module', 'custom_view_modes'),
    ),
  );
}
?> 
