<?php
/**
 * @file
 * Code for the Drupalday System Feature feature.
 */

include_once('drupalday_system_feature.features.inc');


function drupalday_system_feature_user_count() {
  if ($cache = cache_get('dday_user_counter')) {
    return $cache->data;    
  }
  else {
    // permanent cache, it is auto cleared on new user registration
    $count = db_query('SELECT COUNT(uid) FROM {users} where status > 0')->fetchField();
    cache_set('dday_user_counter', $count);
    return $count;
  }
}

/**
 * Implementation of hook_update()
 */
function drupalday_system_feature_user_update(&$edit, $account, $category) {
  if ($account->status != $account->original->status) {
    cache_clear_all('dday_user_counter', 'cache');
  }
}


/**
 * Implements hook_theme()
 */
function drupalday_system_feature_theme() {
  $path = drupal_get_path('module', 'drupalday_system_feature') .'/theme';
  
  return array(
    'render_drupalday_system_feature_user_count' => array(),
    'my_dday' => array(
    	'template' => 'my-dday',
    	'file' => 'theme.inc',
    	'path' => $path,
    ),
  );
}

/**
 * Theme function to render the sole participant number
 * to be called as <?php print theme('render_drupalday_system_feature_user_count'); ?>
 */
function theme_render_drupalday_system_feature_user_count(){
	$output = '<div class="user-count-number"><div class="wrapper">'.drupalday_system_feature_user_count().'<br /><span>iscritti</span></div></div>';
	return $output;
}


/**
 * This function renders the image according the imagecache preset selected
 * object = ( picture, uid )
 * 
 * To be called as it follows theme('avatar', $object, 'avatar_big');
 * 
 * @param unknown_type $form
 */
function theme_avatar($object, $imagecache = 'avatar_medium') {
  $picture = $object->picture;
  /*@TODO: Insert theme( image-style )*/
  /*@TODO: Insert default image avatar in case picture = 0*/
  return $picture;
}