<?php
/**
 * @file
 * Code for the Drupalday System Feature feature.
 */

include_once('drupalday_system_feature.features.inc');


function drupalday_system_feature_user_count() {
  if ($cache = cache_get('dday_user_counter')) {
    return $cache->data;    
  }
  else {
    // permanent cache, it is auto cleared on new user registration
    $count = db_query('SELECT COUNT(uid) FROM {users} where status > 0')->fetchField();
    cache_set('dday_user_counter', $count);
    return $count;
  }
}

/**
 * Implementation of hook_update()
 */
function drupalday_system_feature_user_update(&$edit, $account, $category) {
  if ($account->status != $account->original->status) {
    cache_clear_all('dday_user_counter', 'cache');
  }
}