<!-- Begin MailChimp Signup Form -->
<form action="http://drupalday.us2.list-manage2.com/subscribe/post?u=66540a9e80f31481a0cca2cd5&amp;id=b0c3222212" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank">
<label>
  <span style="font-size:16px;">STAY TUNED!&nbsp</span>Iscriviti alla newsletter per essere subito informato su tutte le novità:
</label>&nbsp;
<input type="text" value="" name="EMAIL" class="required email" id="mce-EMAIL">
<input type="submit" value="Invia" name="subscribe" id="mc-embedded-subscribe" class="btn">
</form>
